# Generated by Django 3.2.12 on 2022-03-04 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('narrators', '0001_initial'),
        ('authors', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('title', models.CharField(max_length=200, verbose_name='title of the book')),
                ('description', models.TextField(max_length=500, verbose_name='description of the book')),
                ('book_cover', models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='book cover of the book')),
                ('book', models.FileField(blank=True, null=True, upload_to='books/book/', verbose_name='book file')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.author')),
                ('categories', models.ManyToManyField(to='categories.Category')),
                ('narrator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='narrators.narrator')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
